### ISSUE TITLE
list all friends and followers and following (for removal).

### ISSUE THREAD

**Issue by hz6** [lida9/CMPUT404-project-socialdistribution#134]

**Comment by yanshan24** [comment]
I un-befriend another user: I stop following them, the other user still a follower of me

**Comment by yanshan24** [comment]
1. I unfollow another user
2. Another user unfollow me

Both use [https://github.com/lida9/CMPUT404-project-socialdistribution/blob/master/project.org#followers](url)
- URL: ://service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}
- DELETE: remove a follower

**Comment by hz6** [comment]
follower listed in /author/followerfriends
you can navigate to it using the 'friend icon' in /aboutme
