### ISSUE TITLE
As an author, I want to befriend remote authors

### ISSUE THREAD

**Issue by lida9** [lida9/CMPUT404-project-socialdistribution#54]

**Comment by yanshan24** [comment]
**For local authors to follow remote users**

- [x] the list of **followings** include local and remote users `GET service/author/<str:authorID>/followings/`
- [x] be able to follow remote users via `PUT /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/`
- [x] be able to stop following remote users via `DELETE /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/`
- [x] be able to check if author is a follower of remote user via `GET /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/`

**To perform from other team's server**
- be able to find local follower in the list using `GET /service/author/{AUTHOR_ID}/followers/`

**Comment by yanshan24** [comment]
**For remote users to follow local users**

- [x] remote users can send friend requests to local users via `POST service/author/<str:authorID>/inbox/` and the request will show up in the inbox
- [x] local users can accept/decline friend requests via `POST service/author/<str:authorID>/inbox/friendrequest/<str:foreignAuthorID>/`
- [x] the list of **followers** include local and remote users `GET service/author/<str:authorID>/followers/`
- [x] be able to check, add, delete a remote follower using `service/author/<str:authorID>/followers/<str:foreignAuthorID>/`

**Comment by yanshan24** [comment]
- [x] the list of friends include local and remote users `GET service/author/<str:authorID>/friends/`

**Comment by yanshan24** [comment]
> **For local authors to follow remote users**
> 
> * [x]  the list of **followings** include local and remote users `GET service/author/<str:authorID>/followings/`
> * [ ]  be able to send friend requests to remote users via `POST /service/author/{AUTHOR_ID}/inbox/` **to their server**
> * [x]  be able to stop following remote users via `DELETE /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/` **to their server**
> * [x]  be able to check if author is a follower of remote user via `GET /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/`
> 
> **To perform from other team's server**
> 
> * be able to find local follower in the list using `GET /service/author/{AUTHOR_ID}/followers/`

- [ ] need to post to the other server so that they know if there are new followers

**Comment by yanshan24** [comment]
> **For remote users to follow local users**
> 
> * [x]  remote users can send friend requests to local users via `POST service/author/<str:authorID>/inbox/` and the request will show up in the inbox
> * [x]  local users can accept/decline friend requests via `POST service/author/<str:authorID>/inbox/friendrequest/<str:foreignAuthorID>/`
> * [x]  the list of **followers** include local and remote users `GET service/author/<str:authorID>/followers/`
> * [x]  be able to check, delete a remote follower using `service/author/<str:authorID>/followers/<str:foreignAuthorID>/`

- [x] need to follow the remote author back if accept the friend request, PUT `/service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/` on their server where `{AUTHOR_ID}` is the remote follower and `{FOREIGN_AUTHOR_ID}` is local user
- [x] if delete a new remote follower, need `DELETE /service/author/{AUTHOR_ID}/followers/{FOREIGN_AUTHOR_ID}/` on their server where `{AUTHOR_ID}` is local user and `{FOREIGN_AUTHOR_ID}` is the remote follower
